config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  resources :lists
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :image

  validates :title, presence: true
  validates :body,  presence: true
  validates :image, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render :new
    end
  end

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    @list.update(list_params)
    redirect_to list_path(@list.id)
  end

  def destroy
    list = List.find(params[:id])
    list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:title, :body, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/homes/top.html.slim
h1.headline-top top

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | SlimApp
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet"
  body
    header
      h1.headline All List
    nav
      ul.nav-list
        li.nav-list-item
          = link_to "Top", root_path
        li.nav-list-item
          = link_to "Lists",  lists_path
        li.nav-list-item
          = link_to "New List", new_list_path
    main
      = yield

app/views/lists/edit.html.slim
.form
  div
    h1 Edit
    - if @list.errors.any?
      = @list.errors.count
      |
        件のエラーが発生しました
      ul
        - @list.errors.full_messages.each do |message|
          li
            = message
    .form-box
      = form_with model: @list do |f|
        h4 Title
        = f.text_field :title
        h4 body
        = f. text_area :body
        h4 Image
        = f.file_field :image, accept: "image/*"
        .button
        = f.submit 'Update'

app/views/lists/index.html.slim
.list-wrap
  - @lists.each do |list|
    .list-box
      - if list.image.attached?
        = image_tag list.image, size: "200x200"
      - else
        = image_tag 'no_image', size: "200x200"
      .list-comment
        span.list-body
          = list.body
        span.list-title
          = link_to list.title, list_path(list.id)

app/views/lists/new.html.slim
.form
  div
    h1 New
    - if @list.errors.any?
      = @list.errors.count
      |
        件のエラーが発生しました
      ul
        - @list.errors.full_messages.each do |message|
          li
            = message
    .form-box
      = form_with model: @list, url: lists_path, method: :post do |f|
        h4 Title
        = f.text_field :title
        h4 Body
        = f.text_area :body
        h4 Image
        = f.file_field :image, accept: "image/*"
        .button
        = f.submit 'Create'

app/views/lists/show.html.slim
.detail
  div
    h2 Title
    p
      = @list.title
    h2 Body
    p
      = @list.body
    h2 Image
    = image_tag @list.image, size: "300x300"
    p
      = link_to "編集", edit_list_path(@list.id)
    p
      = link_to "削除", list_path(@list.id), method: :delete, "data-confirm" => "本当に削除しますか？"